lampo-common/src/model/connect.rs
lampod/src/jsonrpc/peer_control.rs

The application crashes when we try to connect with wrong node id. This commit will fix it.
Co-Developed-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com

fix : unwrap on `Err` inside node_id

---

Makefile

Earlier I noticed that while running `make install` we were getting some error like this :
```
Replaced package `lampod-cli v0.1.0 (/home/harshit/Desktop/lampo.rs/lampod-cli)` with `lampod-cli v0.1.0 (/home/harshit/Desktop/lampo.rs/lampod-cli)` (executable `lampod-cli`)
sudo cp target/debug/liblampo.so /usr/local/lib
[sudo] password for harshit:
cp: cannot stat 'target/debug/liblampo.so': No such file or directory
make: *** [Makefile:22: install] Error 1
```
as we were compiling the lampo in release mode. We were not able to find `target/debug/liblampo.so` as the result was in `target/release/`. Thus, this commit updates the makefile to copy result from `target/release`.

fix : update makefile

---

lampo-common/src/model/getinfo.rs
lampod/src/ln/channel_manager.rs
lampod/src/ln/inventory_manager.rs

We simply get the network from `conf` inside the `CoreWalletManager`. Thus, adding a function inside `CoreWalletManager` to return the chain of network the wallet is built upon.
fixes #183

fix : add network type inside `getinfo`

---

lampo-common/src/model/open_channel.rs
lampod/src/jsonrpc/open_channel.rs
lampod/src/ln/channel_manager.rs
tests/tests/src/lampo_cln_tests.rs

Fixes #174
- Modified `OpenChannel` response struct of `fundchannel` JSON-RPC call to include the funding transaction of type `bitcoin::Transaction` 
- Wait for the `OnChainEvent::SendRawTransaction` event before returning from the JSON-RPC call of `fundchannel`. The timeout is 30 seconds.

Wait for `OnChainEvent::SendRawTransaction` before returning from `fundchannel` RPC call

---

lampo-common/src/event/ln.rs
lampo-common/src/model.rs
lampo-common/src/model/close_channel.rs
lampo-common/src/model/open_channel.rs
lampo-testing/src/lib.rs
lampod-cli/src/main.rs
lampod/src/actions/handler.rs
lampod/src/jsonrpc/channels.rs
lampod/src/ln/channel_manager.rs
lampod/src/ln/events.rs
tests/tests/src/lampo_cln_tests.rs

Adds the ability to close channels from the lampo node.
- Adds close_channel function inside lampod/src/ln/channel_manager.rs
- Adds request/response inside model/close_channel.rs
- Adds `close` command inside main.rs
- Adds `channel_id` inside channels response.
Fixes #195

feat : close channel command

---

lampo-common/src/model/close_channel.rs
tests/tests/src/lampo_cln_tests.rs

Moving `channel_id` test from `lampo_cln_test` to `close_channel.rs` and rename some test names.
Follow up to https://github.com/vincenzopalazzo/lampo.rs/pull/198

refactor : fix some test names and move some test

---

tools/pylampo-client/client.py
tools/pylampo-client/pyproject.toml

This pull request implements `pylampo-client`, a Python client for interacting with Lampo through a Unix socket. It uses Poetry for dependency management.
- Defaults to using `<home_dir>/.lampo/regtest/lampod.socket` for the socket path.
**Related issues**: #132, #139
This client should be used in lnprototest integration testing (See https://github.com/vincenzopalazzo/lampo.rs/issues/139#issuecomment-2004988074) 
```python
from pylampo_client import LampoClient
client = LampoClient()
params = {
"node_id": "<node_id>",
"amount": 100000,
"public": True,
"addr": "<address>",
"port": 19735
}
response = client.call("fundchannel", params)
print(response)
```

Add Lampo Python Client (`pylampo-client`)

---

lampod/src/ln/peer_manager.rs

This pull request fixes #172 , where the application crashes when the specified port is already in use. The crash is occuring cause we are using unwrap() while handling TcpListener::bind().
This commit fixes it by replacing unwrap() with match expressions for error handling.

fix: crash caused when the port is already in use

---

lampo-common/src/conf.rs
lampo-common/src/model/getinfo.rs
lampod/src/ln/channel_manager.rs
lampod/src/ln/inventory_manager.rs

Future fix #192 
- Added `alias`
- Added `blockheight`
- Added `lampo_dir`

Improve `getinfo`

---

Cargo.lock
Cargo.toml
lampo-common/Cargo.toml
lampo-common/src/model/invoice.rs
lampo-common/src/model/open_channel.rs
lampo-testing/src/lib.rs
lampod-cli/src/main.rs
lampod/src/actions/handler.rs
lampod/src/jsonrpc.rs
lampod/src/jsonrpc/offchain.rs
lampod/src/ln/channel_manager.rs
lampod/src/ln/mod.rs
lampod/src/ln/offchain_manager.rs
lampod/src/ln/onion_message.rs
lampod/src/ln/peer_manager.rs
lampod/src/ln/route.rs
tests/tests/src/lampo_cln_tests.rs
tests/tests/src/lampo_tests.rs
tests/tests/src/lib.rs

See commits for more details
The following commit https://github.com/vincenzopalazzo/lampo.rs/commit/0c586b5894aad673354bb2bf1467b77d641e7db3 is a little bit of a mess
Fixes https://github.com/vincenzopalazzo/lampo.rs/issues/193
Fixes https://github.com/vincenzopalazzo/lampo.rs/issues/194
Fixes https://github.com/vincenzopalazzo/lampo.rs/issues/210

adding improvments and also support for bolt12

---

lampo-common/src/conf.rs
lampod/src/ln/peer_manager.rs

This commits adds the ability to announce the IP address where the lampo node can listen for inbound connections.

feat : adds `announce-addr`

---

lampo-bitcoind/src/lib.rs
lampod/src/lib.rs
lampod/src/ln/channel_manager.rs

proto: some dry-by fixes that improve the onchain log

---

lampod-cli/Cargo.toml
lampod-cli/src/args.rs
lampod-cli/src/main.rs

Before this commit the mnemonic was passed by
command line option and it was a privacy leak because the information was stored inside the terminal history.
With this commit, we ask the seeds as input each time that lampo is run with `--restore-wallet` option.
In the future, this option will be required only the first time of initialization of the wallet.
Fixes: https://github.com/vincenzopalazzo/lampo.rs/issues/211
oversees https://github.com/vincenzopalazzo/lampo.rs/pull/213

cli: ask as an input the bip 39

---

Cargo.lock
Cargo.toml
lampo-jsonrpc/src/lib.rs

Alternative version for https://github.com/vincenzopalazzo/lampo.rs/pull/216

Reworking of the jsonrpc server

---

lampo-common/src/model.rs
lampo-common/src/model/getinfo.rs
lampod/src/ln/inventory_manager.rs

This commit adds the address inside `getinfo` command. Changelog:
- Adds `NetworkInfo` response inside lampo_common::model
This is done taking in mind the future work that we do on lampo. 
Sample output for `getinfo` :
```
[doom@archlinux ~]$ lampo-cli --network regtest getinfo
{
"node_id": "02cc3f4c11351843d755569204a69c48cb4233b788392a13d3cf67bb412b14c90f",
"peers": 0,
"channels": 0,
"chain": "regtest",
"alias": "doom",
"blockheight": 105,
"lampo_dir": "/home/doom/.lampo",
"address": [
{
"address": "127.0.0.1",
"port": 39736
}
]
}
```

feat(getinfo) : specify address inside getinfo

---

lampod-cli/src/args.rs

this creates the dir properly downstream
fixes https://github.com/vincenzopalazzo/lampo.rs/issues/232

don't error when datadir doesn't exist

---

README.md
lampo-bdk-wallet/src/lib.rs
lampod-cli/src/main.rs

Clean up README and add warning about Lampo forgetting the seed on restart.
Also fix some typos in log messages.

Clean up README

---

Cargo.lock
lampo-common/src/model/invoice.rs
lampo-core-wallet/Cargo.toml
lampo-core-wallet/src/lib.rs
lampod/src/actions/handler.rs
lampod/src/chain/blockchain.rs
lampod/src/jsonrpc/offchain.rs
lampod/src/ln/offchain_manager.rs
lampod/src/ln/onion_message.rs
lampod/src/ln/peer_manager.rs

Updated LDK to 0.0.123
Updated bdk to 1.0.0-alpha.11
Commits:
* meta: bdk upgrade (adding in the body that this change is required by the bdk change)
*  Updated lampo-core-wallet/Cargo.toml with latest bdk version
*  Used `Xpriv` instead of `ExtendedPrivKey` in lampo-core-wallet/src/lib.rs
* meta: ldk upgrade
* Used `Option<PublicKey>` instead of `String` in lampo-common/src/model/invoice.rs
* Added support for `ldk::events::PaymentPurpose::Bolt12OfferPayment` and `ldk::events::PaymentPurpose::Bolt12RefundPayment` in lampod/src/actions/handler.rs
* Added support for `ConfirmationTarget::OutputSpendingFee` in lampod/src/chain/blockchain.rs
* Updated `create_offer_builder()` in lampod/src/jsonrpc/offchain.rs
* Updated `destination` in lampod/src/ln/onion_message.rs
* Updated …

Lampo updated to LDK 0.0.123

---

lampod/src/lib.rs
lampod/src/utils/logger.rs

ldk was generating a warning log, and we were implementing a wrong match on the string `warning` so the background process was panicking and we were not able to receive the ldk events sometimes.
Fixes: https://github.com/vincenzopalazzo/lampo.rs/issues/218

lampod: fixing panicing of the background task

---

.github/FUNDING.yml
.github/ISSUE_TEMPLATE/bug_report.md

Fixes: https://github.com/vincenzopalazzo/lampo.rs/issues/247

meta: add issue template

---

.github/ISSUE_TEMPLATE/config.yml
Makefile
flake.nix
lampo-common/src/model/invoice.rs
lampo-jsonrpc/src/lib.rs
lampod/src/jsonrpc/offchain.rs
lampod/src/ln/offchain_manager.rs
rust-toolchain
tests/tests/src/lampo_cln_tests.rs
tests/tests/src/lampo_tests.rs

Fixing the following error
➜  ~ lampo-cli --network testnet decode --invoice_str lno1qgsyxjtl6luzd9t3pr62xr7eemp6awnejusgf6gw45q75vcfqqqqqqqgqgn3qzs6danxvetjypnx7u3qwfjhqmmjwss8g6r9yp5hxum4v5tzzqctdp4pvw4zhwsre6ach2mh0ravy52nvjvpg80s5smddzp494px7c {
"code": -1,
"message": "Invalid bech32: invalid checksum",
"data": null
}

lampod: fixing the decode bolt12 offer

---

lampo-common/src/model.rs
lampo-common/src/model/network.rs
lampo-testing/src/lib.rs
lampod/src/jsonrpc/channels.rs
lampod/src/jsonrpc/inventory.rs
lampod/src/ln/channel_manager.rs
tests/tests/src/lampo_cln_tests.rs

This is going to reproduce https://github.com/vincenzopalazzo/lampo.rs/issues/256
Fixes https://github.com/vincenzopalazzo/lampo.rs/issues/256
To run the test consider running `nix develop --command bash -c 'make integration ARGS="-- --test-threads 1 test_sync_gossip_from_network_cln" TEST_LOG_LEVEL=info'` without wasting time in building the test environment.

jsonrpc: add the possibility to fetch the network graph info

---

lampo-common/src/utils/logger.rs

```
2024-08-29T13:14:46.182Z DEBUG   021e9677478fef6e0ff9a64a83f996c7eb31524dc4b7f8b99543224fad3c557885-lightningd: Will try reconnect in 44 seconds
thread 'main' panicked at /home/vincent/.cargo/git/checkouts/lampo.rs-b9f97ec6bc9274e3/c22063d/lampo-common/src/utils/logger.rs:65:53:
called `Result::unwrap()` on an `Err` value: "Unknown gossip level"
```

common: add gossip level as a debug

---

lampod-cli/src/main.rs

Added functionality to store words everytime new wallet is generated or wallet is restored by user.
--restore-wallet reads from the file if it exists, otherwise asks for words from user.

--restore-wallet restores words from file

---

lampo-common/src/model/invoice.rs
lampo-testing/src/lib.rs
lampod/src/jsonrpc/offchain.rs
tests/tests/src/lampo_cln_tests.rs
tests/tests/src/lampo_tests.rs

Decoding bolt12 now:
```
[harshit:~] lampo-cli --network regtest decode --invoice_str lno1qgsyxjtl6luzd9t3pr62xr7eemp6awnejusgf6gw45q75vcfqqqqqqqsespexwyy4tcadvgg89l9aljus6709kx235hhqrk6n8dey98uyuftzdqzrtkahuum7m56dxlnx8r6tffy54004l7kvs7pylmxx7xs4n54986qyqeeuhhunayntt50snmdkq4t7fzsgghpl69v9csgparek8kv7dlp5uqr8ymp5s4z9upmwr2s8xu020d45t5phqc8nljrq8gzsjmurzevawjz6j6rc95xwfvnhgfx6v4c3jha7jwynecrz3y092nn25ek4yl7xp9yu9ry9zqagt0ktn4wwvqg52v9ss9ls22sqyqqestzp2l6decpn87pq96udsvx
{
"issuer": "No issuer id provided",
"offer_id": "[52, 70, 8, 105, 84, 158, 55, 116, 140, 234, 171, 220, 255, 98, 132, 169, 130, 102, 193, 128, 82, 171, 42, 126, 158, 181, 161, 175, 10, 94, 91, 125]",
"offer_chains": [
"43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000"
],
"description": "Description not …
```

Fixes stuff inside bolt12 decode

---

lampo-common/src/model/invoice.rs
lampo-common/src/model/network.rs
lampod/src/jsonrpc/inventory.rs
tests/tests/src/lampo_tests.rs

Fixes #352 and #280
as discussed [here](https://github.com/vincenzopalazzo/lampo.rs/pull/324#discussion_r1948911583) and [here](https://github.com/vincenzopalazzo/lampo.rs/pull/279#discussion_r1687244213)
Also removes hex validation check as discussed https://github.com/vincenzopalazzo/lampo.rs/pull/324#discussion_r1948912438

minor fixes made

---

lampod/src/lib.rs

While we was migrating ldk in https://github.com/vincenzopalazzo/lampo.rs/pull/380 we introduce a regression by returning true and not false inside the sleeper function.
This commit fix the regression and add a test to avoid future regression, and add a comment to clarify it!

core: fix regression in lkd migration

---

Cargo.lock
lampo-common/Cargo.toml
lampo-common/src/keys.rs
lampo-common/src/lib.rs

LDK includes the bolt11 crate within the repository and re-exports it, so we can safely remove the separate dependency.
Fixes: https://github.com/vincenzopalazzo/lampo.rs/issues/405

ldk: remove the ldk bolt11 dependency

---

lampo-bdk-wallet/src/lib.rs

Ensure the blockchain status is checked when the wallet is empty.
Otherwise, the wallet keeps re-indexing the blockchain even if it is empty.
This causes slow startup times when the user uses the wallet for the first time.
Fixes: https://github.com/vincenzopalazzo/lampo.rs/issues/393

bdk: check blockchain status when wallet is empty 

---

lampo-bdk-wallet/src/lib.rs

I am just interested in confirmed transactions in the lightning node, so it probably will make sense to remove the mempool scan
cc @ValuedMammal

bdk: avoid to scan the mempool

---

lampod-cli/src/args.rs
lampod-cli/src/main.rs

This commit refactors the wallet creation logic in lampod-cli into a reusable function create_new_wallet and introduces a new subcommand newwallet. The subcommand allows users to create a new wallet, print the mnemonic to the console, and store it in the default data directory. The existing wallet restoration logic remains unchanged. The changes include: Adding subcommand support with clap in args.rs. Creating a new function for wallet creation in main.rs. Handling the newwallet subcommand to create and display the mnemonic.

Add newwallet subcommand to lampod-cli for wallet creation

---

lampo-testing/src/lib.rs
tests/tests/src/lampo_tests.rs

The `fund_channel_with` function has been refactored so that `self` (the node the method is called on) is the one that initiates and funds the channel to the `counterparty`. The channel direction is now correctly `self -> counterparty`.
Fixes #460

test: corrected `fund_channel_with` to match with its name

---

.github/workflows/audit.yml
.github/workflows/build.yml
.github/workflows/integration_testing.yml
.github/workflows/lnprototest_testing.yml
lampo-testing/src/lib.rs
tests/tests/src/lampo_tests.rs

Previously, the fund_channel_with method was ignoring the amount parameter and always using a hardcoded value of 100000. This fix ensures the method respects the caller's specified amount.
This was likely a regression introduced during refactoring where the hardcoded value was left in place instead of using the function parameter. The fix enables proper testing with different channel amounts and gives callers control over channel funding values.

fix: Use provided amount parameter in fund_channel_with
